project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
    - text: "Aman Arora's Blog"
      href: index.qmd    
    right:
      - icon: github
        href: https://github.com/amaarora
      - icon: twitter
        href: https://twitter.com/amaarora

  # (additional metadata excluded for brevity)
  body-footer: subscribe.html
format:
  html:
    theme: cosmo